apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-image 
  labels: 
    app: myapp
    env: dev
  namespace: devnamespace
  annotations: 
    myecrimage: 542833615945.dkr.ecr.ap-south-1.amazonaws.com/dev1234
spec:
  replicas: 4
  minReadySeconds: 6
  selector:
    matchExpressions: 
      - key: web  # key name and template inside labels name must be same ex: web-->web
        operator: In
        values: 
          - yellowapp-pods
      - key: env
        operator: NotIn
        values: 
          - dev 
      - key: frontend
        operator: Exists
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        web: yellowapp-pods
        env: prod
        frontend: web
      name: podlevellabels 
    spec:
      containers:
        - name: mydeploycon
          image: dheeraj6281/mytemplate:latest
          ports:
            - name: yelloapp-ports
              containerPort: 80
              protocol: TCP
          startupProbe: 
            httpGet:
              path: /
              port: 80 
          livenessProbe: 
            tcpSocket:
              port: 80
          readinessProbe:
            exec:
              command: ["echo" , "higoodmorning"]
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits: 
              cpu: "300m"
              memory: "500Mi"

  